import Head from "next/head";
import styles from "../styles/Home.module.scss";
import FirstText from "../components/first";
import SecondText from "../components/second";
import ThirdText from "../components/third";
import FourthText from "../components/fourth";
import FifthText from "../components/fifth";
import SixthText from "../components/sixth";
import SeventhText from "../components/seventh";
import EighthText from "../components/eighth";
import NinthText from "../components/ninth";
import EleventhText from "../components/Eleventh";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FifthText />
      <FirstText />
      <SecondText />
      <ThirdText />
      <FourthText />
      <SixthText />
      <SeventhText />
      <EighthText />
      <NinthText />
      <EleventhText />
    </div>
  );
}
